### ISSUE TITLE
No pull request possible on empty repo

### ISSUE THREAD

**Issue by CyberSai** [pestphp/pest-dev-tools#1]
As suggested by Nuno Maduro in pestphp/pest#47, It will be nice to refactor all dev dependencies into this repo.

But this not possible since the repo is empty.

I suggest a README is created so that the pull request will be possible.

Thanks.

**Comment by nunomaduro** [comment]
@CyberSai Done. Can you take over on this? The idea is just have a repository that handles all the dev dependencies. Thanks!

**Comment by CyberSai** [comment]
Alright, I created a pull request.

Thanks
